<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * TweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTweetsByAuthor($author_id){
        $query = $this->createQueryBuilder('t')
            ->select(
                't.id, 
                t.text'
            )
            ->join('t.authorId', 'a')
            ->where('t.authorId = :author_id')
            ->setParameter('author_id', (int) $author_id)
            ->getQuery();

        return $query->getResult(Query::HYDRATE_ARRAY);
    }
}
